server:
  port: 8083
spring:
  cloud:
    config:
      server:
        git:
          default-label: testing #aqui elegimos la rama de git
          uri: https://github.com/franco77777/microservices-hexagonal
          search-paths: config-data #escogemos el archivo que usara para configurar la entrada a los otros proyectos
  application:
    name: config-service