server:
  port: 8083
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/franco77777/pragma
          search-paths: config-data
  application:
    name: config-service