server:
  port: 8083
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/franco77777/microservices-hexagonal
          search-paths: config-data
  application:
    name: config-service